# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd Lab2
    npm install
    npm run build
    npm run test
  displayName: 'npm install and test'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Lab2'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure für Bildungseinrichtungen(8cbc67bc-4d42-4f68-8be3-6a039edf574a)'
    appType: 'webApp'
    WebAppName: 'per081022app'
    runtimeStack: 'NODE|16.x'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
    startUpCommand: 'npm run start'